// <auto-generated />
namespace MWC3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddWineToReview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddWineToReview));
        
        string IMigrationMetadata.Id
        {
            get { return "201403080948512_AddWineToReview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
